import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Layout from '@/components/layouts/Layout'
import './globalStyles/header.css'
import './globalStyles/normalize.css'
import './globalStyles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
